apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  namespace: kafka
spec:
  type: ClusterIP
  ports:
  - port: 30091
  # [podname].broker.kafka.svc.cluster.local
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
spec:
  type: NodePort
  ports:
  - name: kafka-client-port
    port: 30092
    nodePort: 30092
  selector:
    app: kafka
