apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-0
  labels:
    app: kafka
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: <path>/kafka-0
    server: <server>
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-1
  labels:
    app: kafka
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: <path>/kafka-1
    server: server
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-kafka-2
  labels:
    app: kafka
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: <path>/kafka-2
    server: <server>
    readOnly: false
