apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-zookeeper-0
  labels:
    app: zookeeper
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: <path>/zookeeper-0
    server: <server>
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-zookeeper-1
  labels:
    app: zookeeper
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: <path>/zookeeper-1
    server: <server>
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-zookeeper-2
  labels:
    app: zookeeper
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: <path>/zookeeper-2
    server: <server>
    readOnly: false
